import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import HeaderTop from './components/headerTop'
import Header from './components/header'
import Footer from './components/footer'
import 'slick-carousel/slick/slick.css'
import 'slick-carousel/slick/slick-theme.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'First Next App',
  description: 'Generated by create first next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 relative">
          <Header/>
          <HeaderTop/>
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  )
}
